# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bc7532f798f698e97bbb0526aa854d5255f901af9a292c07f5f221bf1faa32f8919dbfe5b12191e9594527203d769c7a4bd73b036c02f5319da5e6516df7c12

test:
  secret_key_base: d24fbc06c320eb9a1dd170d072161055dfa2c3b307738466494c3843cd10f253bd983ef04cb66c3b9fe8795950e8960a8d13d507222f489ba0e8d552b8ecc5aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
